### ISSUE TITLE
play online videos

### ISSUE THREAD

**Issue by dynamitemedia** [Kinoma/KPR-examples#60]
will this playe allow for playing of  say a .m3u8 video stream?

**Comment by bfriedk1** [comment]
The [media-player](https://github.com/Kinoma/KPR-examples/tree/master/media-player) sample app can be adapted to play videos from a .m3u8 playlist. The playlist can be parsed by the app at launch. When one video finishes the next video is played by setting the [Media](http://kinoma.com/develop/documentation/javascript/#kinomajs-javascript-reference-kinomajs-object-reference-media-object) object's URL to the next media URL in the playlist. Please feel free to post a question on the [Kinoma Forum](http://forum.kinoma.com/categories/kinoma-coding) if you need more information.
