### ISSUE TITLE
Improperly formatted source code

### ISSUE THREAD

**Issue by johnwargo** [Kinoma/KPR-examples#66]
The source code for the project at https://github.com/Kinoma/KPR-examples/blob/master/web-server/src/main.js isn't formatted correctly WRT linefeeds and so on. The source code doesn't render correctly in GitHub. 
![2016-12-30_10-03-45](https://cloud.githubusercontent.com/assets/571463/21567076/51028e54-ce77-11e6-85d8-3f53ba64a28b.png)

**Comment by lprader** [comment]
Should be fixed now. Thanks for pointing that out.
